---
version: "3.9"

services:
  react-resume:
    container_name: react-resume
    build:
      context: ../
      args:
        environment: local
    image: react-resume
    ports:
      - 11002:80
    environment:
      - PUBLIC_URL=
